version: '3.8'

services:
    app:
        image: laravel:12
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        networks:
            - laravel_network

    postgres:
        image: postgres:16
        container_name: postgres_db
        restart: always
        tty: true
        environment:
            POSTGRES_DB: db_adminlte
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - "4500:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel_network

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        depends_on:
            - postgres
        networks:
            - laravel_network

networks:
    laravel_network:

volumes:
    pgdata:
